grafana:
  ## Grafana's primary configuration
  ## NOTE: values in map will be converted to ini format
  ## ref: http://docs.grafana.org/installation/configuration/
  ##
  grafana.ini:
    server:
      root_url: http://grafana.MINIKUBE_IP.nip.io
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    auth.generic_oauth:
      enabled: true
      scopes: openid profile email
      name: Oauth
      allow_sign_up: true
      client_id: grafana
      client_secret: KEYCLOAK_SECRET
      auth_url: http://keycloak.MINIKUBE_IP.nip.io/auth/realms/grafana/protocol/openid-connect/auth
      token_url: http://keycloak.MINIKUBE_IP.nip.io/auth/realms/grafana/protocol/openid-connect/token
      api_url: http://keycloak.MINIKUBE_IP.nip.io/auth/realms/grafana/protocol/openid-connect/userinfo
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
